"use client";

import { useRevenuePerStore } from "@/hooks/useAnalytics";

export default function RevenueTable() {
  const { data, isLoading, error } = useRevenuePerStore();
console.log("RevenueTable data:", data);
  if (isLoading) {
    return (
      <div className="flex h-60 items-center justify-center">
        <div className="h-10 w-10 animate-spin rounded-full border-4 border-emerald-500 border-t-transparent"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-center text-red-600">
        Failed to load revenue data.
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
      {/* Header */}
      <div className="border-b px-6 py-4">
        <h2 className="text-xl font-semibold text-gray-800">
          Revenue Per Store
        </h2>

        <p className="mt-1 text-sm text-gray-500">
          Total revenue generated by each store.
        </p>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="min-w-full">
          <thead className="bg-slate-100">
            <tr>
              <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">
                Store ID
              </th>

              <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">
                Total Revenue
              </th>
            </tr>
          </thead>

          <tbody className="divide-y divide-gray-200">
            {data?.data.length ? (
              data.data.map(
                (
                  item: {
                    storeId: string;
                    totalRevenue: number;
                  },
                  index: number
                ) => (
                  <tr
                    key={index}
                    className="transition hover:bg-gray-50"
                  >
                    <td className="px-6 py-4 font-medium text-gray-800">
                      {item.storeId}
                    </td>

                    <td className="px-6 py-4">
                    <span className="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-700">
                        ₹{item.totalRevenue.toLocaleString()}
                      </span>
                    </td>
                  </tr>
                )
              )
            ) : (
              <tr>
                <td
                  colSpan={2}
                  className="py-10 text-center text-gray-500"
                >
                  No revenue data available.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}