"use client";

import { useRevenuePerStore } from "@/hooks/useAnalytics";
import { Store, IndianRupee } from "lucide-react";

export default function RevenueTable() {
  const { data, isLoading, error } = useRevenuePerStore();

  if (isLoading) {
    return (
      <div className="rounded-2xl bg-white shadow-sm border border-slate-100 p-8">
        <div className="flex h-60 items-center justify-center">
          <div className="flex flex-col items-center gap-3">
            <div className="h-10 w-10 animate-spin rounded-full border-4 border-emerald-500 border-t-transparent"></div>
            <p className="text-sm text-slate-500">Loading revenue data...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-2xl bg-white shadow-sm border border-red-200 p-8">
        <div className="flex items-center justify-center text-red-600">
          <div className="text-center">
            <p className="font-semibold">Failed to load revenue data</p>
            <p className="text-sm mt-1">Please try again later</p>
          </div>
        </div>
      </div>
    );
  }

  const tableData = data?.data || [];
console.log("tableData",tableData)
  return (
    <div className="rounded-2xl bg-white shadow-sm border border-slate-100 overflow-hidden">
      <div className="border-b border-slate-100 px-6 py-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
              <IndianRupee className="w-5 h-5 text-emerald-600" />
              Revenue Per Store
            </h2>
            <p className="text-sm text-slate-500">Total revenue generated by each store</p>
          </div>
          <span className="text-xs font-medium text-slate-400 bg-slate-50 px-3 py-1 rounded-full">
            {tableData.length} stores
          </span>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full">
          <thead className="bg-slate-50/80">
            <tr>
              <th className="px-6 py-4 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                Store ID
              </th>
                <th className="px-6 py-4 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                Store Name
              </th>
              <th className="px-6 py-4 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                Total Revenue
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {tableData.length > 0 ? (
              tableData.map(
                (
                  item: { storeId: string; totalRevenue: number ;storeName:string},
                  index: number
                ) => (
                  <tr key={index} className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-purple-50 text-purple-600 text-xs font-medium">
                        <Store className="w-3 h-3" />
                        {item.storeId}
                      </span>
                    </td>
                     <td className="px-6 py-4">
                      <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-purple-50 text-purple-600 text-xs font-medium">
                        <Store className="w-3 h-3" />
                        {item.storeName}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-700">
                        <IndianRupee className="w-3.5 h-3.5" />
                        {item.totalRevenue.toLocaleString()}
                      </span>
                    </td>
                  </tr>
                )
              )
            ) : (
              <tr>
                <td colSpan={2} className="py-10 text-center text-slate-500">
                  <div className="flex flex-col items-center gap-2">
                    <IndianRupee className="w-8 h-8 text-slate-300" />
                    <p>No revenue data available</p>
                  </div>
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}